// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDalw6jhnIIt4lThzzGtLElEjaIfbmh4oY',
    appId: '1:735486712668:web:c45bd96087bbd3da80bf99',
    messagingSenderId: '735486712668',
    projectId: 'fypwater-92595',
    authDomain: 'fypwater-92595.firebaseapp.com',
    databaseURL: 'https://fypwater-92595-default-rtdb.firebaseio.com',
    storageBucket: 'fypwater-92595.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtCEgrsASjRmK2jsbWEN5u4FO89F-UefY',
    appId: '1:735486712668:android:f9dd3daac5e931c980bf99',
    messagingSenderId: '735486712668',
    projectId: 'fypwater-92595',
    databaseURL: 'https://fypwater-92595-default-rtdb.firebaseio.com',
    storageBucket: 'fypwater-92595.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChR0MpCH6WYGkH0vBvyNwy03tYQKDRc40',
    appId: '1:735486712668:ios:f7768882a0dee73f80bf99',
    messagingSenderId: '735486712668',
    projectId: 'fypwater-92595',
    databaseURL: 'https://fypwater-92595-default-rtdb.firebaseio.com',
    storageBucket: 'fypwater-92595.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChR0MpCH6WYGkH0vBvyNwy03tYQKDRc40',
    appId: '1:735486712668:ios:f7768882a0dee73f80bf99',
    messagingSenderId: '735486712668',
    projectId: 'fypwater-92595',
    databaseURL: 'https://fypwater-92595-default-rtdb.firebaseio.com',
    storageBucket: 'fypwater-92595.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDalw6jhnIIt4lThzzGtLElEjaIfbmh4oY',
    appId: '1:735486712668:web:b6c0eb81503f0df680bf99',
    messagingSenderId: '735486712668',
    projectId: 'fypwater-92595',
    authDomain: 'fypwater-92595.firebaseapp.com',
    databaseURL: 'https://fypwater-92595-default-rtdb.firebaseio.com',
    storageBucket: 'fypwater-92595.firebasestorage.app',
  );
}
